version: '3'
services:

  # Postgres service
  postgres:
    image: postgres:latest
    ports:
      - "6564:5432"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  # Spring Boot application service
  backend:
    build: .
    ports:
      - "6565:8080"
    depends_on:
      - postgres
