# Server configuration
server:
  port: 8080
  address: /api

# Spring Boot configuration
spring:
  profiles:
    active: dev

  # Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres?createDatabaseIfNotExist=true
    username: root
    password: # default password for postgres is empty

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO
